<style> 
*{
	margin:0px 20px 20px 20px;
}
</style>

	<img style="height:100px;width:290px;" src="images/logo1.png">	
	
	<header class="article-header">

								<h1 style="text-align:center;">TERMS AND CONDITIONS</h1>

							</header> 							<hr/>

							<section class="#" itemprop="articleBody">
								
<h5>On this page and in various sections of the website, www.olympiadfoundation.in (&#8220;Olympiad Foundation website&#8221; or “the website”), are set out the terms and conditions (“Terms”) on which you may access and make use of our website. These Terms constitute a binding legal agreement between you as user (whether or not you are a Registered User, as defined below) and Olympiad Foundation Ltd,(“Olympiad Foundation” or “us”).</h5>
<p><strong>Please read these Terms carefully before you start to use the Olympiad Foundation website. By using the Olympiad Foundation website, you indicate that you accept these Terms and that you agree to abide by them. If you do not agree to these Terms, please refrain from using the Olympiad Foundation website. You warrant that you have the right, authority and capacity to enter into and be bound by these Terms and that by using the Olympiad Foundation website you will not be violating any law or regulation of the country in which you are resident. You are solely responsible for your compliance with all applicable local laws and regulations.</strong></p>
<p><strong>TERMS OF BUSINESS WITH SCHOOLS</strong></p>
<p>In addition to the Terms set out elsewhere on our website, a Client school (via its authorised representative) shall agree to be bound to the following terms of business:</p>
<p><strong>1. </strong><strong>Definitions</strong></p>
<p>In these Terms of Business:</p>
<p>‘Olympiad Foundation’ means Olympiad Foundation Limited.</p>
<p>‘Candidate’ means a person introduced by Olympiad Foundation to the client for the purpose of a permanent, fixed term position or temporary position with the client. This includes teachers a client has connected with via &#8216;Olympiad Foundation Explorer&#8217;.</p>
<p>‘Client’ means the person or organisation within an international school to whom a candidate is introduced. This includes the school itself.</p>
<p>‘Introduce’ means the provision by Olympiad Foundation to the Client of any details, whether written, oral or via the website, of a Candidate.</p>
<p>‘Regulations’ means the Conduct of Employment Agencies and Employment Business Regulations 2003 (as amended from time to time).</p>
<p>‘Terms of Business’ means these Employment Agency Terms of Business, any documents agreed or issued pursuant to the terms herein and any agreed variations.</p>
<p>Reference to the singular includes the plural and reference to the masculine includes any gender and vice versa.</p>
<p><strong>2. </strong><strong>General  </strong></p>
<p>A Candidate is introduced to the Client when Olympiad Foundation supplies, orally, in writing, or via its online platform, any information about the Candidate. A Candidate shall be deemed to have been introduced to the Client unless, within 72 hours (excluding weekends and bank holidays) of delivery to the Client of sufficient information to enable it to identify the Candidate, the Client notifies Olympiad Foundation in good faith that the Candidate is already in contact with the Client about an appointment.</p>
<p><strong>3. </strong><strong>Agreement of Terms of Business</strong></p>
<p>These Terms of Business shall be deemed to have been accepted and agreed by the Client from the time of using any of Olympiad Foundation’ services.</p>
<p><strong>4. </strong><strong>Our Fees</strong></p>
<p>4.1 Fees for Olympiad Foundation  service are charged if Olympiad Foundation is notified within ten days of the contract being signed. If a client fails to notify Olympiad Foundation within ten days, Olympiad Foundation will invoice the client the full fee for our Global service. <strong>See 8 below for the T&amp;Cs for Olympiad Foundation  service.</strong></p>
<p>4.2 Fees for Olympiad Foundation Global service will be charged at the rate agreed with the school. Fees for teachers, middle managers (eg Head of Department) and senior leaders will range depending on the role, the school&#8217;s location and the service required. For more information, email info@olympiadfoundation.in </p>
<p>4.3 Membership of Olympiad Foundation is free and entitles Clients to a school profile page and unlimited &#8216;Basic&#8217; adverts on Olympiad Foundation.</p>
<p>4.4 Olympiad Foundation may alter the fee levels from time to time and, if appropriate, the Client will be advised in writing.</p>
<p><strong>5. Paying the Introductory Fee</strong></p>
<p>5.1 The Client using Olympiad Foundation Global service must notify Olympiad Foundation within 72 hours if they appoint a Candidate whom Olympiad Foundation has introduced.  The Clients using our service must notify Olympiad Foundation within ten working days if they appoint a candidate they found via Olympiad Foundation. We define an appointment to be when there is a written agreement that the Candidate will accept the position, at which point the client will be invoiced.  The Client must pay the agreed fee within 30 days of the date on the invoice. If the Client fails to pay within this agreed period, then Olympiad Foundation shall be entitled to charge interest on any accounts which remain outstanding at the rate of 3% per calendar month or part thereof until the account is settled.</p>
<p>5.2 If a Client fails to pay an agreed introduction fee within 30 days, then Olympiad Foundation reserves the right to cancel the introduction fee and reissue the invoice for the full Global fee listed in our latest brochure. A reminder will be sent when the invoice is overdue.  If the invoice is still not paid within 7 days and a discount is applied, then a new invoice will be issued with the full fee as described in section 4.</p>
<p><strong>6. References</strong></p>
<p>6.1 The Client is responsible for reviewing, checking, and confirming any references (including the confirmation of any professional / academic qualifications and necessary background / safeguarding checks) and shall satisfy itself as to the suitability of any candidates prior to the engagement of a candidate by the Client.</p>
<p>6.2 The Client is responsible for obtaining work permits and/or such other permission to work as may be required, for the arrangement of medical examinations and/or any investigations into the medical history of the Candidate and satisfying any medical or other requirements, qualifications, or permission required by law applicable to the appointment.</p>
<p>6.3 Olympiad Foundation shall endeavour to ensure the suitability of any applicant introduced to the Client and to maintain a high standard of service and integrity, but Olympiad Foundation makes no warranty, express or implied, as to the suitability of any applicant introduced to the Client.</p>
<p>6.4 Olympiad Foundation shall not be liable to the Client for any loss, liability, damage, costs, claims or expenses suffered or incurred by the Client arising from, or connected with, the recruitment or engagement of any candidate by the Client, howsoever arising.</p>
<p>6.5 Candidates cannot access the references provided by current or former employers via their profiles.</p>
<p><strong>7. Rebates</strong></p>
<p>7.1 In the event a Candidate is hired via Olympiad Foundation Global service and does not commence employment or leaves the Client’s employment within 12 weeks of the commencement of employment (for any reason other than redundancy), the Client must notify Olympiad Foundation in writing within one week of the Candidate&#8217;s departure. The Client will then be entitled to a refund of 50% of the recruitment introduction fee.</p>
<p>7.2 For the avoidance of doubt, where the appointment is terminated with no notice, then the relevant period described in clause 7 ends on the date the appointment comes to an end and not (if different) the date when notice is given.</p>
<p>7.3 No refund will be made unless a) the recruitment introduction fee and all other fees and expenses have been paid in accordance with Clause 5; b) written notice is received by Olympiad Foundation within 7 working days of the termination of the candidate&#8217;s engagement; c) the termination in not due to redundancy and d) the Client undertakes not to re-engage the candidate within 12 months of the date of the termination.</p>
<p><strong>8. Olympiad Foundation service</strong></p>
<p>8.1 If a Client clicks on a candidate profile and then interviews and employs the candidate, it counts as an  hire and the Client will be invoiced for that hire. The Client recognises that Olympiad Foundation records every time a Client clicks on a candidate profile and can use this as evidence that the candidate was introduced by Olympiad Foundation.</p>
<p>8.2 If the Client hires a Candidate they have clicked on via our service, the Client must inform Olympiad Foundation within ten days of the candidate agreeing to the offer in writing. If the Client fails to inform Olympiad Foundation within ten days as outlined above, the introductory offer for teachers (for middle leaders and SLT) will no longer apply and Olympiad Foundation will invoice the Client for the full Global hire fee.</p>
<p>8.3 A Client may use both our service and Global services simultaneously. If a Client views, and then contacts a candidate via our service and Olympiad Foundation has already introduced that candidate via our Global service, then the Client will have to pay the agreed Global service fee. If a Client hires a candidate they found via and can provide evidence of contacting the candidate via service and subsequently Olympiad Foundation sends the same candidate to the Client (as a Global candidate), the Client will only pay the service fee as the Client first contacted the Candidate via the system.</p>
<p>8.4 The Client is responsible for its access and information on Olympiad Foundation and agrees never to share its login details with anyone outside the Client’s HR team. If a member of the Client’s HR team leaves the organisation, it is the Client’s responsibility to inform Olympiad Foundation and update the organisation’s login details.</p>
<p>8.5 Olympiad Foundation provides the platform, documentation and references on candidates profiles and does a basic candidate review. However, we expect the Client to be responsible for final background and safeguarding checks according to the Client’s internal policies and to comply with the legal requirement of the Client’s host nation.</p>
<p>8.6 The Client is responsible for the candidates it recruits via Olympiad Foundation . If a candidate is hired via service and the Candidate reneges on the contract with a Client (or leaves employment early), Olympiad Foundation will not provide a refund or offer an alternative Candidate free of charge.</p>
<p>8.7 The Client must keep Olympiad Foundation informed on all progress with candidates and copy <a href="mailto:info@olympiadfoundation.in">info@olympiadfoundation.in</a> on all emails to Olympiad Foundation candidates. Olympiad Foundation reserve the right to cancel the Client’s access to service at any point should they believe the Client is not acting in good faith.</p>
<p>8.8 The Client must never contact a candidate’s referee until the Client has interviewed a candidate (via Zoom or face-to-face) and the candidate (or Olympiad Foundation) has granted permission for his/her referees to be contacted.</p>
<p>8.9 The Client should not send a candidate more than two emails. If a candidate does not respond, the Client should refrain from contacting the candidate again. Clients can contact as many candidates as they wish but we recommend not contacting more than ten candidates for each vacancy per day. If a Client fails to comply with any of our expectations, Olympiad Foundation reserves the right to remove the Client’s access to candidates via our service.</p>
<p><strong>9. </strong><strong>Introductions</strong></p>
<p>9.1 The introduction of a Candidate to a Client by Olympiad Foundation is confidential. The Client must not, directly or indirectly, transfer or introduce a Olympiad Foundation Candidate to any other person, school, firm or company where they are subsequently appointed in a permanent or temporary position within one year of the date of the recruitment introduction of the Candidate to the Client by Olympiad Foundation. If this happens, the Client will have to pay Olympiad Foundation the full recruitment introduction fee,  as if the Client itself had appointed the Candidate.</p>
<p>9.2 When a Candidate is introduced to a Client via the Global service they will receive a &#8216;candidate recommendation&#8217; that includes confidential information about the Candidate. The Client should under no circumstances share this information with the Candidate. Should the Candidate directly or indirectly see the recommendation or its contents, the Client will be held responsible for any losses or damages.</p>
<p>9.3 If a Client agrees to use Olympiad Foundation Global service, the Client agrees to keep Olympiad Foundation copied into all emails to candidates. The Client should first copy in the Olympiad Foundation contact who first introduced the candidate or, in cases this is not possible, the Client should copy in <a href="mailto:info@olympiadfoundation.in">info@olympiadfoundation.in</a></p>
<p>9.4 If a Client agrees to use Olympiad Foundation Global service, the Client agrees to inform Olympiad Foundation of any updates to the status of the Client&#8217;s vacancies and must inform Olympiad Foundation within a week if a vacancy is filled (even if it is not a Olympiad Foundation candidate that has filled the vacancy).</p>
<p>9.5 If Olympiad Foundation introduces a candidate to a Client, the Client should inform Olympiad Foundation of whether or not it intends to interview the candidate within a week of the candidate being put forward. This may be done by replying to the initial email from Olympiad Foundation or by copying Olympiad Foundation in on an email sent directly to the candidate.</p>
<p><b>10. </b><strong>Data protection</strong></p>
<p>The Client and Olympiad Foundation will use and process personal data for recruitment purposes only and in accordance with EU General Data Protection Regulations.</p>

<p><b>11. Modifications to Terms and Conditions</b></p>
<p>Olympiad Foundation can vary these Terms of Business written under LAWS UNDER INDIA, Law by informing clients of changes.</p>
<hr>
<p><strong>WEBSITE USERS TERMS AND CONDITIONS- APPLIES TO SCHOOLS, TEACHERS AND OTHER USERS</strong></p>
<p>Olympiad Foundation is an online collaborative website, that is, a voluntary association of schools and individual teachers working to develop a common database of information on inter-State schools and teachers interested in working in international schools.</p>
<p>The structure of the Olympiad Foundation website used to allow anyone with an internet connection who registers as a “Registered User” to alter the content of their school or teacher content page. Please be advised that whilst we have endeavoured to provide accurate and up-to-date information, nothing found here has necessarily been reviewed by people with the expertise required to provide you with complete, accurate or reliable information.</p>
<p>Olympiad Foundation cannot guarantee the validity of all the information found on the website. If you find any information that you know is not accurate, please contact us on <a href="mailto:info@olympiadfoundation.in">info@olympiadfoundation.in</a> immediately and we will correct it.</p>
<p>As the content of the information on the Olympiad Foundation website is provided by its users, neither Olympiad Foundation nor any of the contributors, administrators, or anyone else connected with Olympiad Foundation in any way what-so-ever is responsible for such information, including the appearance of any inaccurate or libellous information or for your use of the information contained in or linked from the website.</p>
<p>The administrators reserve the right to block any user from using the site for any reason, such as if the user is suspected or found to be sharing inaccurate or unreliable information. Olympiad Foundation is not responsible should someone change, edit, modify or remove any information that you may post on the Olympiad Foundation website or any of its associated projects.</p>
<p><strong>Trademarks</strong></p>
<p>Any of the trademarks or similar rights that are mentioned, used or cited on the Olympiad Foundation website are the property of their respective owners. Olympiad Foundation cannot grant any rights to use any otherwise protected materials. Your use of any such or similar incorporeal property is at your own risk.</p>
<p><strong>Personality rights</strong></p>
<p>The Olympiad Foundation website contains material which may portray an identifiable person who is alive or deceased recently. Before using these types of content, please ensure that you have the right to use it under the laws which apply in the circumstances of your intended use. You are solely responsible for ensuring that you do not infringe someone else&#8217;s personality rights.</p>
<p><strong>Jurisdiction and legality of content</strong></p>
<p>Publication of information found on the Olympiad Foundation website may be in violation of the laws of the country or jurisdiction from where you are viewing this information. Laws in your country or jurisdiction may not protect or allow the same kinds of speech or distribution. Olympiad Foundation does not encourage the violation of any laws; and cannot be responsible for any violations of such laws, should you link to this domain or use, reproduce, or republish the information contained herein.</p>
<p><strong>Further details on our Terms</strong></p>
<p><strong>1. Preliminary</strong></p>
<p>You agree to be subject to these Terms whenever you access the Olympiad Foundation website. In addition, by checking the box next to the &#8220;I have read the Terms of Registered Users and agree with the content” text on the “Create your free teacher profile” page or the “sign in” page and clicking the ‘Create profile’ button, you (the “Registered User”) accept and agree to the  additional teacher terms and conditions (found below) for teacher users or the additional school terms and conditions (found below) for school users and competition rules (found below), as the case may be, and which, for the avoidance of doubt, form part of the Terms. Every time you sign in to access this service you confirm your agreement with the Terms .</p>
<p>You agree to guarantee and hold Olympiad Foundation harmless from any loss, claim or damage, including attorney&#8217;s fees, arising out of or resulting from your use of the website. This includes any violation of the Terms or any action arising from the content that you publish on the website that infringes the intellectual property rights (which include without limitation copyright, trade secrets, trademark or patent) of any third party or content or communication that denigrates, libels or invades the privacy of any third party.</p>
<p><strong>2. Account and password details</strong></p>
<p>The Registered User is solely responsible for maintaining the confidentiality of their Registered User name and password.</p>
<p><strong>3. Content</strong></p>
<p>3.1 You alone are responsible for any content or information you enter on your profile page and any communication with other Registered Users. Olympiad Foundation is not the publisher and only provides the channel for Registered Users to publish and/or distribute their personal information.</p>
<p>3.2 Olympiad Foundation does not verify the accuracy or truth of any information published by Registered Users. No responsibility is assumed by Olympiad Foundation for the publication of any Registered User&#8217;s information, including pictures published by Registered Users.</p>
<p style="margin-left: 14.2pt;">3.4 Please use your common sense when picking the content that you choose to post on or send via Olympiad Foundation because you are solely responsible for, and bear all liability in relation to, such content. You may not publish offensive content, this includes content that contains offensive language, sexually explicit content (including photographs), is unlawful or libellous. Further you may not publish content that encourages behaviour that may constitute a criminal offence, result in civil liability or otherwise violate any applicable local, state, national or international law or regulation. For example, you may <span style="text-decoration: underline;">not</span> post or send any content on the Olympiad Foundation website which:</p>
<ul>
<li style="margin-left: 54pt;">is obscene, pornographic or otherwise may offend human dignity;</li>
<li style="margin-left: 54pt;">is abusive, insulting or threatening, or which promotes or encourages racism, sexism, hatred or bigotry;</li>
<li style="margin-left: 54pt;">incorporates the image or likeness of any individual under 18 years of age;</li>
<li style="margin-left: 54pt;">encourages any illegal activity including, without limitation, terrorism, inciting racial hatred or the submission of which in itself constitutes committing a criminal offence;</li>
<li style="margin-left: 54pt;">is defamatory;</li>
<li style="margin-left: 54pt;">relates to commercial activities (including, without limitation, sales, competitions and advertising, links to other websites or premium line telephone numbers);</li>
<li style="margin-left: 54pt;">involves the transmission of “junk” mail or “spam”;</li>
<li style="margin-left: 54pt;">contains any spy ware, adware, viruses, corrupt files, worm programmes or other malicious code designed to interrupt, damage or limit the functionality of or disrupt any software, hardware, telecommunications, networks, servers or other equipment, Trojan horse or any other material designed to damage, interfere with, wrongly intercept or expropriate any data or personal information whether from Olympiad Foundation or otherwise; or</li>
<li style="margin-left: 54pt;">itself, or the posting of which, infringes any third party’s rights (including, without limitation, intellectual property rights and privacy rights).</li>
</ul>
<p>3.5 Please note though that by posting or sending content on the website you represent and warrant to us that you have the right to do so, and automatically grant to us a non-exclusive, royalty free, perpetual, worldwide licence to use such content in any way (including, without limitation, editing, copying, modifying, adapting, translating, reformatting, creating derivative works from, incorporating into other works, advertising, distributing and otherwise making available to the general public such content, whether in whole or in part and in any format or medium currently known or developed in the future). We may assign and/or sub-licence the above licence to our affiliates and successors without any further approval by you. By submitting content to the website you are warranting that you are the exclusive author and owner of that content and you agree that you waive any and all moral rights relating to that content (including, without limitation, the right to be identified as the author). We have the right to disclose your identity to any third party who is claiming that any content posted or uploaded by you to our website constitutes a violation of their intellectual property rights or of their right to privacy or any other law.</p>
<p style="margin-left: 14.2pt;">3.6 Whilst Olympiad Foundation reserves the right to delete or remove content deemed offensive by Olympiad Foundation, Olympiad Foundation does not guarantee that offensive material will be removed or deleted. Failure by Olympiad Foundation to remove or delete offensive content does not waive our right to remove or delete offensive content in subsequent or similar cases.</p>
<p>3.7 You may not publish content that contains advertising or commercial messages. You may not send messages of a commercial nature to other Registered Users via the site.</p>
<p style="margin-left: 14.2pt;">3.8 Olympiad Foundation reserves the right to refuse to accept, post, display or transmit any user content in its sole discretion.</p>
<p>3.9You may not impersonate any other person or entity.</p>
<p>3.10 You may not solicit other Registered Users&#8217; contact details.</p>
<p>3.11By creating a profile you grant Olympiad Foundation permission to publish your profile (including picture) on <a href="https://www.olympiadfoundation.in/">www.olympiadfoundation.in</a></p>
<p style="margin-left: 14.2pt;">3.12 Your picture and extracts from your profile may be used as a &#8216;featured profile&#8217; for marketing purposes (on the homepage of <a href="https://www.olympiadfoundation.in/">www.olympiadfoundation.in</a> or in our brochures or other marketing materials)</p>
<p>3.13 Olympiad Foundation reserves the right to be able to use screenshots or similar images of pages featured throughout the Olympiad Foundation  service, including the Registered User screen name and photo(s) and use these for general promotional purposes, for example, but not limited to, a corporate brochure, Registered User communications. By creating a profile you grant Olympiad Foundation permission to publish your profile in such a fashion.</p>
<p><strong>4. Copyrighted material</strong></p>
<p>You may not post material belonging to a third party on the site without permission from them. This includes but is not limited to photographs, images and text. Should you believe that material belonging to a third party has been posted on the site you are requested to contact Olympiad Foundation with full details of the alleged copyright infringement including the Registered User username and your contact details.</p>
<p><strong>5. Interaction with other Registered Users</strong></p>
<p>You alone are responsible for ensuring that your interaction with other Registered Users is lawful.</p>
<p>If you encounter information you know is incorrect, please inform the Olympiad Foundation team – <a href="mailto:info@olympiadfoundation.in">info@olympiadfoundation.in</a>. All such issues are treated in confidence, and will be resolved by a senior Registered User of our team as quickly as possible. If deemed appropriate at the sole discretion of Olympiad Foundation, we may warn, suspend or delete a Registered User&#8217;s profile.</p>
<p><strong>6. Registered User communications</strong></p>
<p>Olympiad Foundation does not review or censor other message content, but it reserves the right to remove contact details, or any content deemed to cause offence both school and teacher profile pages.</p>
<p><strong>7. Content storage </strong></p>
<p>Olympiad Foundation assumes no responsibility for the deletion of or failure to store your content, including profile details and photographs. We therefore strongly recommend that you keep a copy of anything that you upload to the Olympiad Foundation website.</p>
<p><strong>8. Registered Users, subscriptions and cancellations</strong></p>
<p style="margin-left: 35.45pt;">8.1 In order to register on the Olympiad Foundation website you must be either a qualified teacher or an international school.</p>
<p style="margin-left: 35.45pt;">8.2 You may register your profile for free and will have access to most of our services. Subscription charges are levied to gain full access to the service for schools, including but not limited to the ability to contact teachers. Subscription is entirely voluntary and you may remain a free Registered User as long as you wish. There are no subscription charges for teachers.</p>
<p>8.3 Olympiad Foundation may change the subscription pricing, options, renewal terms or Registered User services at any time. The Registered User may cancel their subscription at any time. School subscription fees are not transferable from one Registered User profile to another.</p>
<p>8.4 Olympiad Foundation may suspend or terminate the subscription of any Registered User who violates these terms.</p>
<p>8.5 Olympiad Foundation reserves the right not to accept or to suspend or remove from the site all or part of any profile or any other Registered user content for any reason.</p>
<p style="margin-left: 35.45pt;">8.6 Olympiad Foundation reserves the right to remove any job posting or content from the Olympiad Foundation website, which in the reasonable exercise of Teacher’s discretion, does not comply with the Terms, or if any content is posted that Olympiad Foundation believes is not in the best interest of Olympiad Foundation.</p>
<p style="margin-left: 35.45pt;">8.7 Registered teacher users and school users must not publish on your profile any personal contact information, including your address, email address, telephone number, instant messaging contact details or website URL in areas other than the requested fields. In addition, you must not include your personal contact information in messages to members who have not previously contacted you. Olympiad Foundation reserves the right to remove contact details from messages you send on the Olympiad Foundation website.</p>
<p>8.8 Refunds on subscriptions for one off or annual subscriptions will be given to schools at the discretion of Olympiad Foundation management.</p>
<p><strong>9. Modifications to Terms</strong></p>
<p>Olympiad Foundation may modify these Terms from time to time in its sole discretion and/or to take account of new legislation, statutory instruments, Government Regulations, Licences, similar matters and for any other reason. Any such variation shall be published on the website.</p>
<p><strong>10. Legal venue</strong></p>
<p>This agreement will be governed by the laws of England and the parties hereby submit to the exclusive jurisdiction of the Indian courts.</p>
<p><strong>11. Rights of third parties</strong></p>
<p>A person who is not a party to this agreement has no right under the Contracts (Rights of Third Parties) Act 1999 to rely upon or enforce any term of this agreement but this does not affect any right or remedy of a third party which exists or is available apart from that Act.</p>
<p><strong>12. Severability</strong></p>
<p>If any provision in these Terms is deemed to be invalid or unenforceable for any reason, the remaining provisions will continue in full force without being impaired or invalidated in any way.</p>
<p><strong>13. Additional limitation of liability provisions</strong></p>
<p style="margin-left: 35.45pt;">13.1 Olympiad Foundation act as, among other things, venues for (i) employers to post job opportunities and search for and evaluate job candidates and (ii) candidates to post CVs and profiles and search for and evaluate job opportunities. Olympiad Foundation does not screen or censor all of the listings, including profiles offered.</p>
<p style="margin-left: 35.45pt;">13.2 Olympiad Foundation is not involved in the actual transaction between employers and candidates. As a result, Olympiad Foundation is not responsible for user content, the quality, safety or legality of the jobs or CVs posted, the truth or accuracy of the listings, the ability of employers to offer job opportunities to candidates or the ability of candidates to fill job openings and Olympiad Foundation makes no representations about any jobs, CVs or user content on the Olympiad Foundation website. While Olympiad Foundation reserves the right in its sole discretion to remove user content, job postings, CVs or other material from the Olympiad Foundation website from time to time, Olympiad Foundation does not assume any obligation to do so and to the extent permitted by law, disclaims any liability for failing to take any such action.</p>
<p style="margin-left: 35.45pt;">13.3 TO THE FULLEST EXTENT POSSIBLE BY LAW, TEACHER HORIZONS MAXIMUM LIABILITY ARISING OUT OF OR IN CONNECTION WITH ANY TEACHER HORIZON SITE OR YOUR USE OF THE TEACHER HORIZON CONTENT, REGARDLESS OF THE CAUSE OF ACTION (WHETHER IN CONTRACT, TORT, BREACH OF WARRANTY OR OTHERWISE).</p>
<p style="font-size: 12px;">
							</section> 